{% set version = "0.8-9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-r2jags
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/R2jags_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R2jags/R2jags_{{ version }}.tar.gz
  sha256: df06b8f919eed8dd65bca29bbe7e337718142734d6a31818ce1e49db8faee14c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip      # [win]
  host:
    - r-base
    - r-abind
    - r-coda >=0.13
    - r-r2winbugs
    - r-rjags >=3_3
    - r-stringr
    - jags
  run:
    - r-base
    - r-abind
    - r-coda >=0.13
    - r-r2winbugs
    - r-rjags >=3_3
    - r-stringr
    - jags

test:
  commands:
    - $R -e "library('R2jags')"           # [not win]
    - "\"%R%\" -e \"library('R2jags')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=R2jags
  dev_url: https://github.com/suyusung/R2jags/
  license: GPL-2.0-or-later
  summary: Providing wrapper functions to implement Bayesian analysis in JAGS.  Some major features include monitoring convergence of a MCMC model using Rubin and Gelman Rhat statistics, automatically running a MCMC model till it converges, and implementing parallel processing of a MCMC model for multiple chains.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
